# Generated by Django 2.1.4 on 2018-12-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_form_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_newdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.IntegerField()),
                ('course', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Form_details',
        ),
    ]
